steps:
# Add secrets .env and firebase_cert.json
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    rm -f .env firebase_cert.json && \
    gcloud secrets versions access latest --secret=env-dev-camp --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .env && \
    gcloud secrets versions access latest --secret=devcamp-firebase_cert --format='get(payload.data)' | tr '_-' '/+' | base64 -d > firebaseServiceAcc.json
# Build
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA'
  - '.'
# Push
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'push'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA'
# Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - 'run'
  - 'deploy'
  - '$REPO_NAME-$BRANCH_NAME'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA'
  - '--region'
  - 'asia-northeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA'